In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3,4,5]

In [3]:
arr_1 = np.asarray(list_1)

In [4]:
type(arr_1)

numpy.ndarray

In [5]:
arr_1.shape

(5,)

In [6]:
arr_1.ndim

1

In [9]:
arr_1.mean()

3.0

In [11]:
arr_1 = np.arange(20)

In [12]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
arr_1.shape

(20,)

In [15]:
reshaped_array = arr_1.reshape(4,5)

In [16]:
reshaped_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
reshaped_array.shape

(4, 5)

In [18]:
reshaped_array.max(axis=0)

array([15, 16, 17, 18, 19])

In [19]:
reshaped_array.max(axis=1)

array([ 4,  9, 14, 19])

In [20]:
reshaped_array.argmax(axis=0)

array([3, 3, 3, 3, 3])

In [22]:
arr_1 = reshaped_array.reshape(1,-1)

In [23]:
arr_1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [24]:
arr_1.astype(np.int8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]], dtype=int8)

In [25]:
arr_1.T

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [26]:
arr_1 = arr_1.reshape(4,5)

In [27]:
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
arr_1.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [29]:
ones = np.ones(20).reshape(4,5)

In [30]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.zeros(2)

array([0., 0.])

In [33]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [40]:
vec_1 = np.array([1,2,3,4,5])

In [41]:
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
vec_1+arr_1

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14],
       [11, 13, 15, 17, 19],
       [16, 18, 20, 22, 24]])

In [43]:
vec_1.shape

(5,)

In [48]:
vec_1=np.expand_dims(vec_1,axis = 1)

In [49]:
vec_1.shape

(5, 1)

### Note: Keeps on increasing proportionately to the times we run the code

In [68]:
vec_1=np.expand_dims(vec_1,axis=1)

In [69]:
vec_1

array([[[[[[[[[[[1]],

               [[2]],

               [[3]],

               [[4]],

               [[5]]]]]]]]]]])

In [70]:
vec_1.shape

(1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1)

In [71]:
arr_1.shape

(4, 5)

In [75]:
arr_2 = np.arange(20).reshape(5,4)

In [76]:
arr_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [77]:
arr_2.shape

(5, 4)

In [78]:
np.dot(arr_1,arr_2)

array([[120, 130, 140, 150],
       [320, 355, 390, 425],
       [520, 580, 640, 700],
       [720, 805, 890, 975]])

In [79]:
arr_1.dot(arr_2)

array([[120, 130, 140, 150],
       [320, 355, 390, 425],
       [520, 580, 640, 700],
       [720, 805, 890, 975]])

In [80]:
np.append(np.array([1,2,3,4,5]).reshape(1,5),arr_1,axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [83]:
arr_1[1:3,:2]

array([[ 5,  6],
       [10, 11]])

In [88]:
arr_1[2:4,2:4]

array([[12, 13],
       [17, 18]])

In [89]:
arr_1[:,[1,3]]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [90]:
arr_1[:,[0,2]]

array([[ 0,  2],
       [ 5,  7],
       [10, 12],
       [15, 17]])

### Filtering the data

In [92]:
arr_1 >= 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [94]:
arr_1 [arr_1>= 10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [95]:
5.5*arr_1

array([[  0. ,   5.5,  11. ,  16.5,  22. ],
       [ 27.5,  33. ,  38.5,  44. ,  49.5],
       [ 55. ,  60.5,  66. ,  71.5,  77. ],
       [ 82.5,  88. ,  93.5,  99. , 104.5]])